# Nombre de archivo: tests.yml
# Ubicacion de archivo: .github/workflows/tests.yml
# User-provided custom instructions
name: Tests
on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: ./setup_env.sh
      - name: Run pytest
        run: |
          source .venv/bin/activate
          pytest

